---
title: "Resources Compilation"
author: "Ellen Bledsoe"
date: "`r Sys.Date()`"
output: github_document
---

### Course Websites

* Ethan's [Data Carpentry for Biologists](https://datacarpentry.org/semester-biology/) semester course
  * [lecture playlist](https://www.youtube.com/playlist?list=PLD8eCxFKntVH5EJmTBaZXWaU8cM_T9Lfl)
* [Kerkoff's EcoInformatics Course](https://globalecologybiogeography.github.io/Ecoinformatics/)
* The Carpentries
  * [Data Carpentry R for Ecologists lesson](https://datacarpentry.org/R-ecology-lesson/index.html)
  * [Data Carpentry R for Ecologists Rewrite](https://www.michaelc-m.com/Rewrite-R-ecology-lesson/)
  * [Software Carpentry: R for Reproducible Scientific Analysis](https://swcarpentry.github.io/r-novice-gapminder/guide/)
  * [Software Carpentry: Programming with R](http://swcarpentry.github.io/r-novice-inflammation/)
* [Bahlai's Guide for Reproducible Quantitative Methods courses](https://cbahlai.github.io/rqm-template/)
* [Simona's EcoRepSci course (graduate)](https://ecorepsci.github.io/reproducible-science/)
* [Jeff Oliver's learn-r page](https://jcoliver.github.io/learn-r/)
* [Jarrett Byrnes's Intro to Data Science for Biologists course](https://biol355.github.io/)
  * includes links to lecture slides, lectures, class pre-readings, etc.
  * [lecture playlist](https://www.youtube.com/playlist?list=PLZRMqMK8aRmL9UqEsi_uT-JHkloZEwHUn)
  * most readings from Wickham and Grolemund's [R for Data Science](https://r4ds.had.co.nz/)
* [Dan McGlinn's Applied Quantitative Methods course](http://dmcglinn.github.io/quant_methods/)
* [NEON Learning Hub](https://www.neonscience.org/resources/learning-hub)
* [QUBES FMN site](https://qubeshub.org/community/fmns)
* see Catherine's course on D2L
  * [YouTube channel](https://www.youtube.com/channel/UCAxw75f8aIKi-ciS5PM_qmg/videos) for the course
* [Data Science in a Box](https://datasciencebox.org/)
  * [GitHub repo for the course](https://github.com/rstudio-education/datascience-box)


### Books which teach R
* [R for Data Science by Wickham & Grolemund](https://r4ds.had.co.nz/)

### Videos Teaching R
* Kelsey Gonzalez's [YouTube channel](https://www.youtube.com/playlist?list=PL6FsZxVq54ERrlMRNE5aq2qUFH042fbuM)
* Ethan White's [Data Carpentry for Biologists playlist](https://www.youtube.com/playlist?list=PLD8eCxFKntVH5EJmTBaZXWaU8cM_T9Lfl)
* Jarrett Byrnes's [Intro Data Science for Biologists playlist](https://www.youtube.com/playlist?list=PLZRMqMK8aRmL9UqEsi_uT-JHkloZEwHUn)

### Pedagogy Resources
* [Martin Monkman's R Resource Compendium](https://bookdown.org/martin_monkman/DataScienceResources_book/data-science-pedagogy.html)
* Data Science in a Box (see above) [Pedagogy Tips](https://datasciencebox.org/04-pedagogy.html)
* see "VCU_DataScience" group library on Zotero

### Possible Data Sources
* [NEON](https://www.neonscience.org/data-samples)
* [LTER and GLEON data (via Environmental Data Initiative Portal)](https://portal.edirepository.org/nis/advancedSearch.jsp)
* [Ecological Data Wiki](https://ecologicaldata.org/)
* [DataONE](https://old.dataone.org/data)
* Large public datasets listed [here](https://github.com/awesomedata/awesome-public-datasets#biology), including agriculture, biology, climate + weather, earth science, energy, etc.)
* [VertNet](http://vertnet.org/)
* Living Data Project data (location?)
* Berkeley Earth [climate data](http://berkeleyearth.org/data/)

#### Data Packages
* [`popler`](https://docs.ropensci.org/popler/)
* [`lterdatasampler`](https://lter.github.io/lterdatasampler/)
* [`rdataretriever`](https://github.com/ropensci/rdataretriever)
* [`portalr`](https://weecology.github.io/portalr/)
  * [`ratdat`](https://github.com/weecology/ratdat), the Portal teaching data set
* [`palmerpenguins`](https://allisonhorst.github.io/palmerpenguins/)
* [`tidybiology`](https://github.com/matthewhirschey/tidybiology)
